/** Declaration file generated by dts-gen */

export = password_prompt;

declare function password_prompt(ask: any, options: any): any;

declare namespace password_prompt {
    const prototype: {
    };

}

